name: Format

on:
  workflow_run:
    workflows: ["Format Check"]
    types: [completed]
  push:
    branches: [ main ]

jobs:
  formatting:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v4.0.0
        with:
          args: "--skip-sorting-imports --replace"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Apply Google Java Format
          branch: format-changes
          title: Apply Google Java Format
          body: This PR applies the Google Java Format to the codebase.
          labels: formatting
