name: Format

on:
  push:
    branches: [ Development_Branch ]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v2 minimum required
      - uses: axel-op/googlejavaformat-action@v4.0.0
        with:
          args: "--skip-sorting-imports --replace"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Apply Google Java Format
          branch: format-changes
          title: Apply Google Java Format
          body: This PR applies the Google Java Format to the codebase.
          labels: formatting
