name: Format Check

on: [ push, pull_request ]

jobs:

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v2 minimum required
      - uses: actions/axel-op/googlejavaformat-action@4
        with:
          release-name: "1.25.2"
          args: "--set-exit-if-changed"
